### PR TITLE
Add LIST, FROZENSET and DUP opcodes

### PR DESCRIPTION
**Pull request by 00xc**
* `LIST`: builds a list out of the topmost stack slice until it reaches a markobject.
* `FROZENSET`: builds a frozenset out of the topmost slice until it reaches a markobject.
* `DUP`: pushes the top stack item onto the stack again, duplicating it.

### CODE REVIEW

**Comment by woodruffw** [comment]
Thanks @00xc, this looks great! I'm going to get #41 merged first, but once that's in this'll be next.

**Comment by 00xc** [comment]
> Thanks @00xc, this looks great! I'm going to get #41 merged first, but once that's in this'll be next.

Okay, thanks!

**Comment by woodruffw** [comment]
```
. env/bin/activate && \
	black --check fickling/pickle.py fickling/analysis.py fickling/cli.py fickling/__init__.py fickling/tracing.py fickling/__main__.py test/test_pickle.py test/__init__.py test/test_crashes.py example/pytorch_poc.py example/numpy_poc.py example/fault_injection.py example/inject_mobilenet.py  && \
	ruff fickling
would reformat fickling/pickle.py

Oh no! 💥 💔 💥
1 file would be reformatted, 12 files would be left unchanged.
```

Try running `make format` locally 🙂

**Comment by 00xc** [comment]
> ```
> . env/bin/activate && \
> 	black --check fickling/pickle.py fickling/analysis.py fickling/cli.py fickling/__init__.py fickling/tracing.py fickling/__main__.py test/test_pickle.py test/__init__.py test/test_crashes.py example/pytorch_poc.py example/numpy_poc.py example/fault_injection.py example/inject_mobilenet.py  && \
> 	ruff fickling
> would reformat fickling/pickle.py
> 
> Oh no! 💥 💔 💥
> 1 file would be reformatted, 12 files would be left unchanged.
> ```
> 
> Try running `make format` locally slightly_smiling_face

All done I think

**Comment by 00xc** [comment]
Ping?

**Comment by woodruffw** [comment]
Sorry for the delay! Doing a last pass now.

**Comment by woodruffw** [comment]
Thanks again @00xc!

**Pull request merged**
